language: node_js

# test against all active LTS and latest stable
node_js:
  - "4"
  - "6"
  - "8"
  - "node"

cache:
  directories:
    - "node_modules"

after_success: npm run coverage

notifications:
  email:
    on_success: never
