# file validation
# https://docs.travis-ci.com/user/travis-lint

language: node_js

node_js:
  - "node" # always last (stable) version
  - "lts/*" # always last LTS version
  - "lts/boron" # previous LTS, still in maintenance

cache:
  directories:
    - "node_modules"

after_success: npm run coverage

notifications:
  email:
    on_success: never

# Greenkeeper lockfile https://github.com/greenkeeperio/greenkeeper-lockfile
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
